# fly.toml app configuration file generated for spork-portfell on 2025-04-22T20:52:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spork-portfell'
primary_region = 'arn'

[build]

[env]
  PORT = '4000'
  PHX_HOST = 'spork-porfell.fly.dev'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
